# Generated by Django 5.2.7 on 2025-11-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Licence_no',
            new_name='License_no',
        ),
    ]
